### ISSUE TITLE
Incorrect setting of boundary

### ISSUE THREAD

**Issue by jaimiejellema** [BlainMaguire/3dfluid#1]
The function set_bnd() does not properly handle the 12 edges of the cube.
It only sets 6 faces, and 8 corners.

For each face you loop from 1 to N meaning you do not handle the 0 and N+1 edge.
I think a solution would be to set each of the edge cells equal to the average of the 2 neighbors, which are not part of the edge.

**Comment by BlainMaguire** [comment]
Well spotted. Looks like something I never got around to adding while porting over from 2D.

In the GUI, I have it hard coded to apply forces from the center of the grid to the center of the faces. So it may be possible to get away with boundary conditions for just the 6 faces.

A quick way to test would be change that code to apply forces at a 45 degree angle towards the edges of the cube instead. If you're seeing anything strange in that case, I'm happy to take a look or accept a pull request.

**Comment by jaimiejellema** [comment]
The boundary box provided by just the faces is sufficient to contain the fluid.
How ever the density along the edges does not reflect the density nearby.
It is hard to visualize but some printf debugging shows that along the edges the density is always zero.

This means that there is a cut out along the edges of the cube where the density is zero.
(clear_data function resets all values to 0).

**Comment by BlainMaguire** [comment]
Okay, I see what you mean now. Merged in the code you submitted. Thanks for the contribution!
